

spring:
  application:
    name: user-service
    datasource:
        name: database
        url: jdbc:mysql://localhost:3306/db_4bhome
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: false
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.111.1:8761/eureka/
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.zzd.bean